export const LIST_CREATING = 'LIST_CREATING'  
export const LIST_CREATE_SUCCESS = 'LIST_CREATE_SUCCESS'  
export const LIST_CREATE_ERROR = 'LIST_CREATE_ERROR'

export const LIST_SET = 'LIST_SET'
export const LIST_SET_CURRENT ='LIST_SET_CURRENT'

export const LIST_UPDATING = 'LIST_UPDATING'
export const LIST_UPDATE_SUCCESS = 'LIST_UPDATE_SUCCESS'
export const LIST_UPDATE_ERROR = 'LIST_UPDATE_ERROR'

export const LIST_DELETING = 'LIST_DELETING'
export const LIST_DELETE_SUCCESS = 'LIST_DELETE_SUCCESS'
export const LIST_DELETE_ERROR = 'LIST_DELETE_ERROR'

export const CARD_LIST_CREATE_SUCCESS = 'CARD_LIST_CREATE_SUCCESS'
export const CARD_LIST_DELETE_SUCCESS = 'CARD_LIST_DELETE_SUCCESS'