module.exports = {
	SYSTEM: {
		ATTEMPT_REGISTER: 'ATTEMPT_REGISTER',
		SUCCESS_REGISTER: 'SUCCESS_REGISTER',
		FAILURE_REGISTER: 'FAILURE_REGISTER'
	},
	CLIENT: {
		ATTEMPT_LOGIN: 'ATTEMPT_LOGIN',
		SUCCESS_LOGIN: 'SUCCESS_LOGIN',
		FAILURE_LOGIN: 'FAILURE_LOGIN'
	},
	INTERNAL: {
		GET_USERS: 'GET_USERS'
	}
};
