export const BOARD_CREATING = 'BOARD_CREATING'  
export const BOARD_CREATE_SUCCESS = 'BOARD_CREATE_SUCCESS'  
export const BOARD_CREATE_ERROR = 'BOARD_CREATE_ERROR'

export const BOARD_REQUESTING = 'BOARD_REQUESTING'
export const BOARD_REQUEST_SUCCESS = 'BOARD_REQUEST_SUCCESS'
export const BOARD_REQUEST_ERROR = 'BOARD_REQUEST_ERROR'