export const BOARD_CREATING = 'BOARD_CREATING'  
export const BOARD_CREATE_SUCCESS = 'BOARD_CREATE_SUCCESS'  
export const BOARD_CREATE_ERROR = 'BOARD_CREATE_ERROR'

export const BOARD_SET = 'BOARD_SET'
export const BOARD_SET_CURRENT ='BOARD_SET_CURRENT'

export const BOARD_UPDATING = 'BOARD_UPDATING'
export const BOARD_UPDATE_SUCCESS = 'BOARD_UPDATE_SUCCESS'
export const BOARD_UPDATE_ERROR = 'BOARD_UPDATE_ERROR'

export const BOARD_DELETING = 'BOARD_DELETING'
export const BOARD_DELETE_SUCCESS = 'BOARD_DELETE_SUCCESS'
export const BOARD_DELETE_ERROR = 'BOARD_DELETE_ERROR'

