// Authenticaiton
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_FORM_ERRORS = 'LOGIN_FORM_ERRORS'
export const LOGOUT_USER = 'LOGOUT_USER'

// User
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

// Board
export const GET_BOARD_REQUEST = 'GET_BOARD_REQUEST'
export const GET_BOARD_FAILURE = 'GET_BOARD_FAILURE'
export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'
export const UPDATE_BOARD_REQUEST = 'UPDATE_BOARD_REQUEST'
export const UPDATE_BOARD_FAILURE = 'UPDATE_BOARD_FAILURE'
export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS'
export const DELETE_BOARD_REQUEST = 'DELETE_BOARD_REQUEST'
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE'
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS'
export const CREATE_BOARD_REQUEST = 'CREATE_BOARD_REQUEST'
export const CREATE_BOARD_FAILURE = 'CREATE_BOARD_FAILURE'
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS'

// LIST
export const UPDATE_LIST_REQUEST = 'UPDATE_LIST_REQUEST'
export const UPDATE_LIST_FAILURE = 'UPDATE_LIST_FAILURE'
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS'
export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST'
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE'
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS'