export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_GET_FAILURE = "USERS_GET_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const BOARDS_REQUEST = "BOARDS_REQUEST";
export const BOARDS_GET_SUCCESS = "BOARDS_GET_SUCCESS";
export const BOARDS_GET_FAILURE = "BOARDS_GET_FAILURE";

export const LISTS_REQUEST = "LISTS_REQUEST";
export const LISTS_GET_SUCCESS = "LISTS_GET_SUCCESS";
export const LISTS_GET_FAILURE = "LISTS_GET_FAILURE";

export const CARDS_REQUEST = "CARDS_REQUEST";
export const CARDS_GET_SUCCESS = "CARDS_GET_SUCCESS";
export const CARDS_GET_FAILURE = "CARDS_GET_FAILURE";

export const BASE_URL = "djello/api";
