export const CARD_CREATING = 'CARD_CREATING'  
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS'  
export const CARD_CREATE_ERROR = 'CARD_CREATE_ERROR'

export const CARD_SET = 'CARD_SET'

export const CARD_UPDATING = 'CARD_UPDATING'
export const CARD_UPDATE_SUCCESS = 'CARD_UPDATE_SUCCESS'
export const CARD_UPDATE_ERROR = 'CARD_UPDATE_ERROR'

export const CARD_DELETING = 'CARD_DELETING'
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS'
export const CARD_DELETE_ERROR = 'CARD_DELETE_ERROR'

export const CARD_LIST_CREATE_SUCCESS = 'CARD_LIST_CREATE_SUCCESS'
export const CARD_LIST_DELETE_SUCCESS = 'CARD_LIST_DELETE_SUCCESS'

export const LIST_CARD_DELETE_SUCCESS = 'LIST_CARD_DELETE_SUCCESS'
export const BOARD_LIST_CARD_DELETE_SUCCESS = 'BOARD_LIST_CARD_DELETE_SUCCESS'